# general configuration
url: http://jared.sart.in
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "https://www.gravatar.com/avatar/eca6a30157569c5a522f406240de6977"
  # author will appear under the avatar (optional)
  author: "Jared Sartin"
  # tagline will appear under the title (optional)
  tagline: "Creative Technologist, Web Dev, Product Lead, Data Nerd, Dungeon Master"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: true
  # Twitter @username (as defined by the Twitter Card specs)
  twitter: "JaredSartin"

# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
